"""
The "traffic controller" for saving generated models.

The AI brain lives in `modules.py`. This file only:
  • calls that brain with your text
  • saves the answer as a real Python file in the repo
  • remembers which service actually answered (Groq, Mistral, Ollama, …) so we can
    write a tiny note at the top of the file like a sticker on a school project.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from .modules import ArchitectureGenerator

# Turn short names (used inside the code) into nicer names people recognize.
PROVIDER_LABELS = {
    "groq": "Groq",
    "gemini": "Google Gemini",
    "cohere": "Cohere",
    "mistral": "Mistral AI",
    "ollama": "Ollama (local)",
}


def generation_header(backend: str, model: str, base_url: str | None) -> str:
    """Build the few comment lines that go above the generated PyTorch file."""
    provider = PROVIDER_LABELS.get(backend, backend)
    lines = [
        "# Auto-generated by tools/model_plugin_dspy_ali",
        f"# Organization / provider: {provider}",
        f"# Model: {model}",
    ]
    if base_url:
        # Only Ollama needs its computer address written down here.
        lines.append(f"# Ollama API base: {base_url}")
    return "\n".join(lines) + "\n\n"


class ModelPluginAliPipeline:
    """One object you call with a string; you get a dict back plus a file on disk."""

    def __init__(
        self,
        ollama_model: str | None = None,
        ollama_base_url: str | None = None,
        repo_root: str | Path | None = None,
    ) -> None:
        self.ollama_model = ollama_model
        self.ollama_base_url = ollama_base_url
        # Root folder of the whole project (where `plugins/` lives). We default to
        # "go up two folders from this file" if the caller does not pass a path.
        if repo_root is not None:
            self.repo_root = Path(repo_root)
        else:
            self.repo_root = Path(__file__).resolve().parents[2]
        self._generator: ArchitectureGenerator | None = None

    @property
    def generator(self) -> ArchitectureGenerator:
        # Create the AI helper only once; reuse it for later runs.
        if self._generator is None:
            self._generator = ArchitectureGenerator(
                ollama_model=self.ollama_model,
                ollama_base_url=self.ollama_base_url,
            )
        return self._generator

    def run(self, prompt: str) -> dict[str, Any]:
        """Main public method: prompt text in, summary dictionary out (and file saved)."""
        request = prompt.strip()
        if not request:
            raise ValueError("prompt must be non-empty")

        architecture = self.generator(prompt=request)
        output_model = self._write_architecture(
            architecture.code,
            backend=architecture.backend,
            model=architecture.model,
            base_url=architecture.base_url,
        )
        return {
            "approach": "dspy_chain_of_thought_fewshot",
            "backend": architecture.backend,
            "model": architecture.model,
            "base_url": architecture.base_url,
            "output_model": str(output_model),
            "architecture": architecture.code,
        }

    def _write_architecture(
        self,
        code: str,
        *,
        backend: str,
        model: str,
        base_url: str | None,
    ) -> Path:
        """Stick the header sticker on, then write the body of the Python model file."""
        output_model = (
            self.repo_root
            / "plugins"
            / "models"
            / "generated_architecture"
            / "customized_model_ali.py"
        )
        output_model.parent.mkdir(parents=True, exist_ok=True)
        body = code.rstrip() + "\n"
        header = generation_header(backend, model, base_url)
        output_model.write_text(header + body, encoding="utf-8")
        return output_model
