"""Central configuration for config_plugin_dspy (no hard-coded secrets elsewhere)."""

from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path

ENV_OLLAMA_BASE_URL = "FC_DSPY_OLLAMA_BASE_URL"
ENV_OLLAMA_MODEL = "FC_DSPY_OLLAMA_MODEL"

DEFAULT_OLLAMA_BASE_URL = "http://localhost:11434"
DEFAULT_OLLAMA_MODEL = "llama3.1"

GROQ_LITELLM_MODEL = "groq/mixtral-8x7b-32768"
GEMINI_LITELLM_MODEL = "gemini/gemini-1.5-pro"
COHERE_LITELLM_MODEL = "cohere/command-r-plus"
MISTRAL_LITELLM_MODEL = "mistral/codestral-latest"

BACKEND_GROQ = "groq"
BACKEND_GEMINI = "gemini"
BACKEND_COHERE = "cohere"
BACKEND_MISTRAL = "mistral"
BACKEND_OLLAMA = "ollama"

PROVIDER_DISPLAY_NAMES: dict[str, str] = {
    BACKEND_GROQ: "Groq",
    BACKEND_GEMINI: "Google Gemini",
    BACKEND_COHERE: "Cohere",
    BACKEND_MISTRAL: "Mistral AI",
    BACKEND_OLLAMA: "Ollama (local)",
}

TEMPLATE_FILENAME = "config.maximum.yml"
OUTPUT_PATH_PARTS: tuple[str, ...] = ("tools", "output", "config", "generated")
OUTPUT_FILENAME = "config.generated.plugin.yml"

PACKAGE_TOOL_NAME = "tools/config_plugin_dspy"
PIPELINE_APPROACH = "config_plugin_dspy_bootstrap_fewshot"
AUTO_GEN_HEADER_LINE = f"# Auto-generated by {PACKAGE_TOOL_NAME}"

BOOTSTRAP_MAX_BOOTSTRAPPED_DEMOS = 6
INTENT_EXTRACT_MAX_RETRIES = 3


@dataclass(frozen=True)
class Settings:
    groq_api_key: str
    gemini_api_key: str
    cohere_api_key: str
    mistral_api_key: str
    groq_litellm_model: str
    gemini_litellm_model: str
    cohere_litellm_model: str
    mistral_litellm_model: str
    default_ollama_base_url: str
    default_ollama_model: str
    template_filename: str
    output_path_parts: tuple[str, ...]
    output_filename: str
    package_tool_name: str
    pipeline_approach: str
    provider_display_names: dict[str, str]
    bootstrap_max_bootstrapped_demos: int
    intent_extract_max_retries: int


def _secret(*names: str) -> str:
    for name in names:
        value = os.environ.get(name)
        if value and str(value).strip():
            return str(value).strip()
    try:
        import tools.local_secrets as local_secrets

        for name in names:
            if hasattr(local_secrets, name):
                value = getattr(local_secrets, name)
                if value and str(value).strip():
                    return str(value).strip()
    except ImportError:
        pass
    return ""


def load_settings() -> Settings:
    return Settings(
        groq_api_key=_secret("GROQ_API_KEY", "FC_DSPY_GROQ_API_KEY"),
        gemini_api_key=_secret("GEMINI_API_KEY", "FC_DSPY_GEMINI_API_KEY"),
        cohere_api_key=_secret("COHERE_API_KEY", "FC_DSPY_COHERE_API_KEY"),
        mistral_api_key=_secret("MISTRAL_API_KEY", "FC_DSPY_MISTRAL_API_KEY"),
        groq_litellm_model=GROQ_LITELLM_MODEL,
        gemini_litellm_model=GEMINI_LITELLM_MODEL,
        cohere_litellm_model=COHERE_LITELLM_MODEL,
        mistral_litellm_model=MISTRAL_LITELLM_MODEL,
        default_ollama_base_url=DEFAULT_OLLAMA_BASE_URL,
        default_ollama_model=DEFAULT_OLLAMA_MODEL,
        template_filename=TEMPLATE_FILENAME,
        output_path_parts=OUTPUT_PATH_PARTS,
        output_filename=OUTPUT_FILENAME,
        package_tool_name=PACKAGE_TOOL_NAME,
        pipeline_approach=PIPELINE_APPROACH,
        provider_display_names=dict(PROVIDER_DISPLAY_NAMES),
        bootstrap_max_bootstrapped_demos=BOOTSTRAP_MAX_BOOTSTRAPPED_DEMOS,
        intent_extract_max_retries=INTENT_EXTRACT_MAX_RETRIES,
    )


def resolve_ollama_base_url(explicit: str | None) -> str:
    if explicit is not None and explicit.strip():
        return explicit.strip().rstrip("/")
    raw = os.environ.get(ENV_OLLAMA_BASE_URL, DEFAULT_OLLAMA_BASE_URL)
    return str(raw).strip().rstrip("/")


def resolve_ollama_model(explicit: str | None) -> str:
    if explicit is not None and explicit.strip():
        return explicit.strip()
    return str(os.environ.get(ENV_OLLAMA_MODEL, DEFAULT_OLLAMA_MODEL)).strip()


def template_path(repo_root: Path, settings: Settings) -> Path:
    return repo_root / settings.template_filename
