"""
All tunable values for model_plugin_dspy_majid live here.

Nothing in other modules should hard-code API keys, model names, or output paths.
Environment variables can override Ollama host and model when set.
"""

from __future__ import annotations

import os
from dataclasses import dataclass

# Environment variable names, It will be used to get the ollama base URL and model name

ENV_OLLAMA_BASE_URL = "FC_DSPY_OLLAMA_BASE_URL"
ENV_OLLAMA_MODEL = "FC_DSPY_OLLAMA_MODEL"

# Defaults model -> ollama
DEFAULT_OLLAMA_BASE_URL = "http://localhost:11434"
DEFAULT_OLLAMA_MODEL = "llama3.1"

# Cloud API keys: read from tools/keys_secrets.py (gitignored)
try:
    from tools.keys_secrets import (
        GROQ_API_KEY,
        GEMINI_API_KEY,
        COHERE_API_KEY,
        MISTRAL_API_KEY,
    )
except ImportError:
    GROQ_API_KEY = ""
    GEMINI_API_KEY = ""
    COHERE_API_KEY = ""
    MISTRAL_API_KEY = ""

# Candidate Models
GROQ_LITELLM_MODEL = "groq/mixtral-8x7b-32768"
GEMINI_LITELLM_MODEL = "gemini/gemini-1.5-pro"
COHERE_LITELLM_MODEL = "cohere/command-r-plus"
MISTRAL_LITELLM_MODEL = "mistral/codestral-latest"

# Short Keys
BACKEND_GROQ = "groq"
BACKEND_GEMINI = "gemini"
BACKEND_COHERE = "cohere"
BACKEND_MISTRAL = "mistral"
BACKEND_OLLAMA = "ollama"

# Header comments
PROVIDER_DISPLAY_NAMES: dict[str, str] = {
    BACKEND_GROQ: "Groq",
    BACKEND_GEMINI: "Google Gemini",
    BACKEND_COHERE: "Cohere",
    BACKEND_MISTRAL: "Mistral AI",
    BACKEND_OLLAMA: "Ollama (local)",
}

# Out put directory and file name
OUTPUT_PATH_PARTS: tuple[str, ...] = ("plugins", "models", "generated_architecture")
OUTPUT_FILENAME = "customized_model_majid.py"

# Metadata strings
PACKAGE_TOOL_NAME = "tools/model_plugin_dspy_majid"
PIPELINE_APPROACH = "dspy_chain_of_thought_fewshot"

# Header template lines (provider and model filled at write time)
AUTO_GEN_HEADER_LINE = f"# Auto-generated by {PACKAGE_TOOL_NAME}"

# A class used only to define only attributes without any function
@dataclass(frozen=True)
class Settings:
    """ All needed data"""

    groq_api_key: str
    gemini_api_key: str
    cohere_api_key: str
    mistral_api_key: str
    groq_litellm_model: str
    gemini_litellm_model: str
    cohere_litellm_model: str
    mistral_litellm_model: str
    default_ollama_base_url: str
    default_ollama_model: str
    output_path_parts: tuple[str, ...]
    output_filename: str
    package_tool_name: str
    pipeline_approach: str
    provider_display_names: dict[str, str]


def load_settings() -> Settings:
    """Build settings from module-level constants (single place for configuration)."""
    return Settings(
        groq_api_key=GROQ_API_KEY,
        gemini_api_key=GEMINI_API_KEY,
        cohere_api_key=COHERE_API_KEY,
        mistral_api_key=MISTRAL_API_KEY,
        groq_litellm_model=GROQ_LITELLM_MODEL,
        gemini_litellm_model=GEMINI_LITELLM_MODEL,
        cohere_litellm_model=COHERE_LITELLM_MODEL,
        mistral_litellm_model=MISTRAL_LITELLM_MODEL,
        default_ollama_base_url=DEFAULT_OLLAMA_BASE_URL,
        default_ollama_model=DEFAULT_OLLAMA_MODEL,
        output_path_parts=OUTPUT_PATH_PARTS,
        output_filename=OUTPUT_FILENAME,
        package_tool_name=PACKAGE_TOOL_NAME,
        pipeline_approach=PIPELINE_APPROACH,
        provider_display_names=dict(PROVIDER_DISPLAY_NAMES),
    )


def resolve_ollama_base_url(explicit: str | None) -> str:
    """Return ollama base URL"""
    if explicit is not None and explicit.strip():
        # Read the explicit URL for other models except ollama
        return explicit.strip().rstrip("/")
    
    try:
        # Get ollama base URL from environment variable
        # If not found, use default
        raw = os.environ.get(ENV_OLLAMA_BASE_URL, DEFAULT_OLLAMA_BASE_URL)
        
        # Return the ollama base URL
        return str(raw).strip().rstrip("/")
    
    except Exception as exc:
        
        # If failed, raise an error
        raise RuntimeError("Failed to resolve Ollama base URL from environment.") from exc


def resolve_ollama_model(explicit: str | None) -> str:
    """Return ollama model name"""
    if explicit is not None and explicit.strip():
        # Read the explicit model name for other models except ollama
        return explicit.strip()
    
    try:
        # Get ollama model name from environment variable
        # If not found, use default
        return str(os.environ.get(ENV_OLLAMA_MODEL, DEFAULT_OLLAMA_MODEL)).strip()
    
    except Exception as exc:
        
        # If failed, raise an error
        raise RuntimeError("Failed to resolve Ollama model name from environment.") from exc
