# Auto-generated by tools/model_plugin_dspy_v2
# Organization / provider: Mistral AI
# Model: codestral-latest

import torch
import torch.nn as nn
import torch.nn.functional as F


class Model(nn.Module):

    def __init__(self, n_classes, in_features):
        super(Model, self).__init__()
        self.conv1 = nn.Conv2d(in_features, 10, kernel_size=5)
        self.conv2 = nn.Conv2d(10, 20, kernel_size=5)
        self.conv2_drop = nn.Dropout2d()
        self.pool = nn.MaxPool2d(2)
        self.act = nn.ReLU()
        self.fc1 = nn.Linear(320, 50)
        self.drop = nn.Dropout()
        self.fc2 = nn.Linear(50, n_classes)

    def forward(self, x):
        x = self.act(self.pool(self.conv1(x)))
        x = self.act(self.pool(self.conv2_drop(self.conv2(x))))
        x = x.view(-1, 320)
        x = self.act(self.fc1(x))
        x = self.drop(x)
        x = self.fc2(x)
        return F.log_softmax(x, dim=1)
