from __future__ import annotations

"""Render PluginModelDesign as plugins/models Python source (no LLM)."""

from pathlib import Path

from .modules import PluginModelDesign


def render_model_file(design: PluginModelDesign) -> str:
    imports = ["import torch", "import torch.nn as nn"]
    if design.use_functional_softmax:
        imports.append("import torch.nn.functional as F")
    header = "\n".join(imports) + "\n\n\n"

    notes = design.notes.replace("\n", " ").strip()
    notes_line = f"        # {notes}\n" if notes else ""

    init_lines = _render_init_lines(design)
    forward_body = _render_forward_body(design)

    body = (
        "class Model(nn.Module):\n"
        '    """Auto-generated by tools/model_plugin_dspy (layered architecture)."""\n\n'
        "    def __init__(self, n_classes, in_features):\n"
        "        super(Model, self).__init__()\n"
        f"{notes_line}"
        f"{init_lines}\n"
        "    def forward(self, x):\n"
        f"{forward_body}\n"
    )
    return header + body


def _render_init_lines(design: PluginModelDesign) -> str:
    parts: list[str] = []
    for m in design.modules:
        parts.append("        " + _module_ctor_line(m))
    return "\n".join(parts)


def _module_ctor_line(m: dict) -> str:
    name = m["name"]
    t = m["type"]
    if t == "Conv2d":
        if m.get("use_in_features_for_in_channels"):
            in_expr = "in_features"
        else:
            in_expr = str(int(m["in_channels"]))
        oc = int(m["out_channels"])
        ks = int(m["kernel_size"])
        pad = int(m["padding"])
        st = int(m.get("stride", 1))
        return (
            f"self.{name} = nn.Conv2d({in_expr}, {oc}, kernel_size={ks}, padding={pad}, stride={st})"
        )
    if t == "MaxPool2d":
        k = int(m["kernel_size"])
        return f"self.{name} = nn.MaxPool2d({k})"
    if t == "ReLU":
        return f"self.{name} = nn.ReLU()"
    if t == "SiLU":
        return f"self.{name} = nn.SiLU()"
    if t == "BatchNorm1d":
        nf = int(m["num_features"])
        return f"self.{name} = nn.BatchNorm1d({nf})"
    if t == "Dropout2d":
        p = float(m.get("p", 0.0))
        if p > 0.0:
            return f"self.{name} = nn.Dropout2d(p={p})"
        return f"self.{name} = nn.Dropout2d()"
    if t == "Dropout":
        p = float(m.get("p", 0.5))
        return f"self.{name} = nn.Dropout({p})"
    if t == "AdaptiveAvgPool2d":
        h, w = m["output_size"]
        return f"self.{name} = nn.AdaptiveAvgPool2d(({int(h)}, {int(w)}))"
    if t == "Flatten":
        sd = int(m.get("start_dim", 1))
        ed = int(m.get("end_dim", -1))
        return f"self.{name} = nn.Flatten(start_dim={sd}, end_dim={ed})"
    if t == "Linear":
        inf = int(m["in_features"])
        if m.get("out_features_from_n_classes"):
            return f"self.{name} = nn.Linear({inf}, n_classes)"
        return f"self.{name} = nn.Linear({inf}, {int(m['out_features'])})"
    raise ValueError(f"Unknown module type: {t}")


def _render_forward_body(design: PluginModelDesign) -> str:
    lines: list[str] = []
    for step in design.forward:
        if "apply" in step:
            mod = step["apply"]
            lines.append(f"        x = self.{mod}(x)")
        elif "view" in step:
            a, b = step["view"]
            lines.append(f"        x = x.view({int(a)}, {int(b)})")
        elif "flatten" in step:
            sd = int(step["flatten"]["start_dim"])
            lines.append(f"        x = torch.flatten(x, start_dim={sd})")
        elif "log_softmax" in step:
            dim = int(step["log_softmax"])
            lines.append(f"        return F.log_softmax(x, dim={dim})")
            return "\n".join(lines)
        elif step.get("return_logits"):
            lines.append("        return x")
            return "\n".join(lines)
    lines.append("        return x")
    return "\n".join(lines)


def write_model_file(target_path: str | Path, content: str) -> Path:
    p = Path(target_path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding="utf-8")
    return p
