"""Central configuration for model_plugin_dspy_v2 (no hard-coded values elsewhere)."""

from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path

# ENV variable names for the Ollama base URL and model if it is installed locally
ENV_OLLAMA_BASE_URL = "FC_DSPY_OLLAMA_BASE_URL"
ENV_OLLAMA_MODEL = "FC_DSPY_OLLAMA_MODEL"


# Open WebUI OpenAI-compatible API (POST {base}/chat/completions).
DEFAULT_OLLAMA_BASE_URL = "https://dev.chat.cosy.bio/api"
DEFAULT_OLLAMA_MODEL = "llama4:latest"
COSY_MODEL_CASCADE: tuple[str, ...] = (
    "qwen3.5:122b",
    "gpt-oss:120b",
    "qwen3.6:27b",
    "gemma4:31b",
    "llama4:latest",
)

# API keys: read from tools/keys_secrets.py (gitignored)
try:
    from tools.keys_secrets import (
        GROQ_API_KEY,
        GEMINI_API_KEY,
        COHERE_API_KEY,
        MISTRAL_API_KEY,
        COSY_API_KEY,
    )
except ImportError:
    GROQ_API_KEY = ""
    GEMINI_API_KEY = ""
    COHERE_API_KEY = ""
    MISTRAL_API_KEY = ""
    COSY_API_KEY = ""

# Candidate Models for the different providers
GROQ_LITELLM_MODEL = "groq/mixtral-8x7b-32768"
GEMINI_LITELLM_MODEL = "gemini/gemini-1.5-pro"
COHERE_LITELLM_MODEL = "cohere/command-r-plus"
MISTRAL_LITELLM_MODEL = "mistral/codestral-latest"

# Backend keys for the different providers
BACKEND_GROQ = "groq"
BACKEND_GEMINI = "gemini"
BACKEND_COHERE = "cohere"
BACKEND_MISTRAL = "mistral"
BACKEND_OLLAMA = "ollama"


# Provider display names for the different providers dictionary
PROVIDER_DISPLAY_NAMES: dict[str, str] = {
    BACKEND_GROQ: "Groq",
    BACKEND_GEMINI: "Google Gemini",
    BACKEND_COHERE: "Cohere",
    BACKEND_MISTRAL: "Mistral AI",
    BACKEND_OLLAMA: "Ollama (COSY.BIO)",
}


# Output path parts for the generated
OUTPUT_PATH_PARTS: tuple[str, ...] = ("plugins", "models", "generated_architecture")

# Output filename for the generated model architecture implementation
OUTPUT_FILENAME = "customized_model_v2.py"


# Package tool name for the tool
PACKAGE_TOOL_NAME = "tools/model_plugin_dspy_v2"

# Pipeline approach for the tool
PIPELINE_APPROACH = "dspy_v2_bootstrap_fewshot"
AUTO_GEN_HEADER_LINE = f"# Auto-generated by {PACKAGE_TOOL_NAME}"

# It can be defined how many few-shot examples to use for the bootstrap
# Total few-shots in fewshot_examples.py: 12
BOOTSTRAP_MAX_BOOTSTRAPPED_DEMOS = 10

# --recompile convention (same as the other DSPy agents): True = compile with
# BootstrapFewShot and save the compiled agent; False = load the saved agent.
RECOMPILE = True
ENV_RECOMPILE = "FC_DSPY_RECOMPILE"
COMPILED_PROGRAM_DIR_NAME = "compiled_agent"
COMPILED_PROGRAM_FILENAME = "compiled_agent.json"

# RAG knobs only (corpus path, top-k). Retrieval logic lives in rag/, not here.
RAG_ENABLED = True
RAG_TOP_K = 3
RAG_CORPUS_REL: tuple[str, ...] = ("plugins", "models")
RAG_EXCLUDE_DIR_NAMES: tuple[str, ...] = ("generated_architecture",)
# Saved plugins (e.g. c_f_test1.py) stay in the index so name-based prompts can retrieve them.
RAG_EXCLUDE_FILENAMES: tuple[str, ...] = ()
RAG_INDEX_DIR_NAME = "rag_index"
RAG_MAX_CHUNK_CHARS = 8000
RAG_MAX_PROMPT_CHARS = 6000

# To just keep the settings in one place
@dataclass(frozen=True)
class Settings:
    groq_api_key: str
    gemini_api_key: str
    cohere_api_key: str
    mistral_api_key: str
    cosy_api_key: str
    groq_litellm_model: str
    gemini_litellm_model: str
    cohere_litellm_model: str
    mistral_litellm_model: str
    default_ollama_base_url: str
    default_ollama_model: str
    cosy_model_cascade: tuple[str, ...]
    output_path_parts: tuple[str, ...]
    output_filename: str
    package_tool_name: str
    pipeline_approach: str
    provider_display_names: dict[str, str]
    bootstrap_max_bootstrapped_demos: int
    rag_enabled: bool
    rag_top_k: int
    rag_corpus_rel: tuple[str, ...]
    rag_exclude_dir_names: tuple[str, ...]
    rag_exclude_filenames: tuple[str, ...]
    rag_index_dir_name: str
    rag_max_chunk_chars: int
    rag_max_prompt_chars: int


def load_settings() -> Settings:
    return Settings(
        groq_api_key=GROQ_API_KEY,
        gemini_api_key=GEMINI_API_KEY,
        cohere_api_key=COHERE_API_KEY,
        mistral_api_key=MISTRAL_API_KEY,
        cosy_api_key=COSY_API_KEY,
        groq_litellm_model=GROQ_LITELLM_MODEL,
        gemini_litellm_model=GEMINI_LITELLM_MODEL,
        cohere_litellm_model=COHERE_LITELLM_MODEL,
        mistral_litellm_model=MISTRAL_LITELLM_MODEL,
        default_ollama_base_url=DEFAULT_OLLAMA_BASE_URL,
        default_ollama_model=DEFAULT_OLLAMA_MODEL,
        cosy_model_cascade=COSY_MODEL_CASCADE,
        output_path_parts=OUTPUT_PATH_PARTS,
        output_filename=OUTPUT_FILENAME,
        package_tool_name=PACKAGE_TOOL_NAME,
        pipeline_approach=PIPELINE_APPROACH,
        provider_display_names=dict(PROVIDER_DISPLAY_NAMES),
        bootstrap_max_bootstrapped_demos=BOOTSTRAP_MAX_BOOTSTRAPPED_DEMOS,
        rag_enabled=RAG_ENABLED,
        rag_top_k=RAG_TOP_K,
        rag_corpus_rel=RAG_CORPUS_REL,
        rag_exclude_dir_names=RAG_EXCLUDE_DIR_NAMES,
        rag_exclude_filenames=RAG_EXCLUDE_FILENAMES,
        rag_index_dir_name=RAG_INDEX_DIR_NAME,
        rag_max_chunk_chars=RAG_MAX_CHUNK_CHARS,
        rag_max_prompt_chars=RAG_MAX_PROMPT_CHARS,
    )

# Tryto find the Ollama url by giving it, if it is not found, use the env or
# default url
def resolve_ollama_base_url(explicit: str | None) -> str:
    if explicit is not None and explicit.strip():
        return explicit.strip().rstrip("/")
    try:
        raw = os.environ.get(ENV_OLLAMA_BASE_URL, DEFAULT_OLLAMA_BASE_URL)
        return str(raw).strip().rstrip("/")
    except Exception as exc:
        raise RuntimeError("Failed to resolve Ollama base URL from environment.") from exc


# Tryto find the Ollama model by giving it, if it is not found, use the env or
# default model
def resolve_ollama_model(explicit: str | None) -> str:
    if explicit is not None and explicit.strip():
        return explicit.strip()
    try:
        return str(os.environ.get(ENV_OLLAMA_MODEL, DEFAULT_OLLAMA_MODEL)).strip()
    except Exception as exc:
        raise RuntimeError("Failed to resolve Ollama model name from environment.") from exc


def resolve_recompile(explicit: bool | None = None) -> bool:
    if explicit is not None:
        return bool(explicit)
    raw = os.environ.get(ENV_RECOMPILE)
    if raw is not None and raw.strip():
        return raw.strip().lower() not in ("0", "false", "no")
    return RECOMPILE
