"""Central configuration for model_plugin_dspy_v2 (no hard-coded values elsewhere)."""

from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path

# ENV variable names for the Ollama base URL and model if it is installed locally
ENV_OLLAMA_BASE_URL = "FC_DSPY_OLLAMA_BASE_URL"
ENV_OLLAMA_MODEL = "FC_DSPY_OLLAMA_MODEL"


# Default Ollama base URL and model which is in docker container(mostly this part is being used when the user is not using the local ollama)
DEFAULT_OLLAMA_BASE_URL = "http://localhost:11434"
DEFAULT_OLLAMA_MODEL = "llama3.1"

# API keys: read from tools/keys_secrets.py (gitignored)
try:
    from tools.keys_secrets import (
        GROQ_API_KEY,
        GEMINI_API_KEY,
        COHERE_API_KEY,
        MISTRAL_API_KEY,
    )
except ImportError:
    GROQ_API_KEY = ""
    GEMINI_API_KEY = ""
    COHERE_API_KEY = ""
    MISTRAL_API_KEY = ""

# Candidate Models for the different providers
GROQ_LITELLM_MODEL = "groq/mixtral-8x7b-32768"
GEMINI_LITELLM_MODEL = "gemini/gemini-1.5-pro"
COHERE_LITELLM_MODEL = "cohere/command-r-plus"
MISTRAL_LITELLM_MODEL = "mistral/codestral-latest"

# Backend keys for the different providers
BACKEND_GROQ = "groq"
BACKEND_GEMINI = "gemini"
BACKEND_COHERE = "cohere"
BACKEND_MISTRAL = "mistral"
BACKEND_OLLAMA = "ollama"


# Provider display names for the different providers dictionary
PROVIDER_DISPLAY_NAMES: dict[str, str] = {
    BACKEND_GROQ: "Groq",
    BACKEND_GEMINI: "Google Gemini",
    BACKEND_COHERE: "Cohere",
    BACKEND_MISTRAL: "Mistral AI",
    BACKEND_OLLAMA: "Ollama (local)",
}


# Output path parts for the generated
OUTPUT_PATH_PARTS: tuple[str, ...] = ("plugins", "models", "generated_architecture")

# Output filename for the generated model architecture implementation
OUTPUT_FILENAME = "customized_model_v2.py"


# Package tool name for the tool
PACKAGE_TOOL_NAME = "tools/model_plugin_dspy_v2"

# Pipeline approach for the tool
PIPELINE_APPROACH = "dspy_v2_bootstrap_fewshot"
AUTO_GEN_HEADER_LINE = f"# Auto-generated by {PACKAGE_TOOL_NAME}"

# It can be defined how many few-shot examples to use for the bootstrap
BOOTSTRAP_MAX_BOOTSTRAPPED_DEMOS = 10

# To just keep the settings in one place
@dataclass(frozen=True)
class Settings:
    groq_api_key: str
    gemini_api_key: str
    cohere_api_key: str
    mistral_api_key: str
    groq_litellm_model: str
    gemini_litellm_model: str
    cohere_litellm_model: str
    mistral_litellm_model: str
    default_ollama_base_url: str
    default_ollama_model: str
    output_path_parts: tuple[str, ...]
    output_filename: str
    package_tool_name: str
    pipeline_approach: str
    provider_display_names: dict[str, str]
    bootstrap_max_bootstrapped_demos: int


def load_settings() -> Settings:
    return Settings(
        groq_api_key=GROQ_API_KEY,
        gemini_api_key=GEMINI_API_KEY,
        cohere_api_key=COHERE_API_KEY,
        mistral_api_key=MISTRAL_API_KEY,
        groq_litellm_model=GROQ_LITELLM_MODEL,
        gemini_litellm_model=GEMINI_LITELLM_MODEL,
        cohere_litellm_model=COHERE_LITELLM_MODEL,
        mistral_litellm_model=MISTRAL_LITELLM_MODEL,
        default_ollama_base_url=DEFAULT_OLLAMA_BASE_URL,
        default_ollama_model=DEFAULT_OLLAMA_MODEL,
        output_path_parts=OUTPUT_PATH_PARTS,
        output_filename=OUTPUT_FILENAME,
        package_tool_name=PACKAGE_TOOL_NAME,
        pipeline_approach=PIPELINE_APPROACH,
        provider_display_names=dict(PROVIDER_DISPLAY_NAMES),
        bootstrap_max_bootstrapped_demos=BOOTSTRAP_MAX_BOOTSTRAPPED_DEMOS,
    )

# Tryto find the Ollama url by giving it, if it is not found, use the env or
# default url
def resolve_ollama_base_url(explicit: str | None) -> str:
    if explicit is not None and explicit.strip():
        return explicit.strip().rstrip("/")
    try:
        raw = os.environ.get(ENV_OLLAMA_BASE_URL, DEFAULT_OLLAMA_BASE_URL)
        return str(raw).strip().rstrip("/")
    except Exception as exc:
        raise RuntimeError("Failed to resolve Ollama base URL from environment.") from exc


# Tryto find the Ollama model by giving it, if it is not found, use the env or
# default model
def resolve_ollama_model(explicit: str | None) -> str:
    if explicit is not None and explicit.strip():
        return explicit.strip()
    try:
        return str(os.environ.get(ENV_OLLAMA_MODEL, DEFAULT_OLLAMA_MODEL)).strip()
    except Exception as exc:
        raise RuntimeError("Failed to resolve Ollama model name from environment.") from exc
